# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  fonts:
    - "node_modules/@fortawesome/fontawesome-free/webfonts"
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
